# Generated by Django 5.0.2 on 2024-02-23 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='category',
            new_name='category_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
